### ISSUE TITLE
Wrong lib version

### ISSUE THREAD

**Issue by Tigerskunk** [stefanbylund/zxnext_sprite#1]
When trying to compile with:
zcc +zxn -subtype=nex -vn -SO3 -startup=31 -clib=sdcc_iy --max-allocs-per-node200000 -llib/zxn/zxnext_sprite  main.c -o zxnext_sprite_demo -create-app              

, I get told:
 
library file '/Users/tigerSkunk/Downloads/z88dk/libsrc/_DEVELOPMENT/lib/sdcc_iy/lib/zxn/zxnext_sprite.lib' version 12, expected version 13

**Comment by Xalior** [comment]
This is because you are using an older version of the library (or, rather, compiled with an older version of z88dk) than the version of Z88dk you are running --  you can fix this by rebuilding the library with your currently installed version, and linking to the newly produced .lib file.

Good luck!

-Dx

**Comment by Tigerskunk** [comment]
I did a "make all" in the zxnext_sprite-master folder like advised in the readme and copied the resulting .h and .lib files where they are referenced.

Seems the problem prevails when I try to compile.

Any further ideas :) ? Would really love to use this lovely libs... :)

**Comment by stefanbylund** [comment]
Hi @Tigerskunk ! I'm sorry for replying so late but I had missed to enable e-mail notifications on my GitHub account.

@Xalior explained the problem and its solution well. You need to rebuild the zxnext_sprite library with your newer version of z88dk. I can see that you managed to do a new build using "make clean all" but you fail to link with your rebuilt library.

Here is an example of how to link with the zxnext_sprite library:
https://github.com/stefanbylund/zxnext_sprite_demo/blob/master/Makefile

Here is a command-line snippet for building using the sdcc_iy flavour with the zxnext_sprite project located one directory level up from your project:

`zcc +zxn -subtype=nex -vn -SO3 -startup=31 -clib=sdcc_iy -m --max-allocs-per-node200000 -L$../zxnext_sprite/lib/sdcc_iy -lzxnext_sprite -I../zxnext_sprite/include my_program.c -o my_program -create-app`
